import type { Language } from '../types/portfolio'

const es = {
  skip: 'Saltar al contenido',
  navLabel: 'Navegación principal',
  language: 'Cambiar idioma',
  cases: 'Arquitectura',
  philosophy: 'Filosofía',
  leadership: 'Liderazgo',
  career: 'Trayectoria',
  contact: 'Hablemos',
  loading: 'Cargando portafolio…',
  updating: 'Actualizando idioma…',
  retry: 'Volver a intentar',
  loadError: 'No pude cargar el portafolio. Intenta nuevamente.',
  timeout: 'La conexión está tardando más de lo esperado. Intenta nuevamente.',
  heroFirst: 'Arquitectura con criterio.',
  heroSecond: 'Código con intención.',
  heroFallback:
    'Ingeniería de producto, decisiones de arquitectura y liderazgo técnico con participación directa en el código.',
  explore: 'Explorar decisiones',
  startConversation: 'Iniciar una conversación',
  terminalLabel: 'Una forma de pensar en sistemas',
  terminalTitle: 'engineering.md',
  terminalProblem: 'Entender el problema',
  terminalDecide: 'Hacer explícitos los trade-offs',
  terminalBuild: 'Construir, medir, mejorar',
  terminalPrinciple: 'La claridad también escala.',
  metricsLabel: 'Resultados de un caso de producción',
  p99: 'Latencia P99',
  peak: 'Eventos por segundo',
  before: 'antes',
  after: 'después',
  metricsNote: 'Caso AdTech · métricas de producción',
  skillsEyebrow: '04 / herramientas',
  skillsTitle: 'El stack sigue al problema.',
  skillsDescription:
    'Tecnología elegida con contexto. Sistemas que se pueden operar y mantener.',
  casesEyebrow: '02 / decisiones de producción',
  casesTitle: 'Decisiones, no recetas.',
  casesDescription:
    'El contexto, la solución y el coste de elegirla. Así pienso la arquitectura.',
  context: 'Contexto',
  problem: 'El problema',
  solution: 'La decisión',
  tradeoffs: 'Los trade-offs',
  impact: 'Impacto',
  technicalDetails: 'Ver razonamiento técnico',
  metricBefore: 'P99 antes',
  metricAfter: 'P99 después',
  metricPeak: 'Pico de eventos',
  philosophyEyebrow: '01 / forma de trabajar',
  philosophyTitle: 'Menos suposiciones. Más evidencia.',
  philosophyDescription:
    'Principios que llegan al código, a los incidentes y a cada decisión de producto.',
  leadershipEyebrow: '03 / liderazgo técnico',
  leadershipTitle: 'El equipo también es arquitectura.',
  leadershipDescription:
    'Crear contexto para que otras personas puedan tomar mejores decisiones.',
  careerEyebrow: '05 / trayectoria',
  careerTitle: 'Cerca del código. Responsable del rumbo.',
  contactEyebrow: '06 / conversación',
  contactTitle: '¿Qué problema estamos resolviendo?',
  contactDescription:
    'Cuéntame el contexto, la fricción y lo que necesitas cambiar. Empecemos por entenderlo.',
  contactNote:
    'Tu mensaje se usa únicamente para responder a esta conversación.',
  name: 'Nombre',
  email: 'Correo electrónico',
  subject: 'Asunto',
  message: 'Mensaje',
  optional: 'opcional',
  namePlaceholder: 'Tu nombre',
  emailPlaceholder: 'tu@empresa.com',
  subjectPlaceholder: '¿En qué estás trabajando?',
  messagePlaceholder: 'El contexto, el desafío y qué te gustaría conseguir…',
  messageHint: 'Entre 15 y 3000 caracteres.',
  send: 'Enviar mensaje',
  sending: 'Enviando…',
  received: 'Solicitud recibida. Gracias por compartir el contexto.',
  contactError:
    'No pude enviar el mensaje. Revisa tu conexión e intenta nuevamente.',
  contactTimeout:
    'No pude confirmar la recepción. Espera antes de reenviar para evitar duplicados.',
  invalidContact: 'Revisa los campos indicados antes de enviar.',
  rateLimit:
    'Has enviado varias solicitudes. Espera {minutes} min antes de intentar otra vez.',
  nameRequired: 'Escribe tu nombre.',
  nameLong: 'El nombre no debe superar 100 caracteres.',
  emailInvalid: 'Escribe un correo válido, con un máximo de 255 caracteres.',
  subjectLong: 'El asunto no debe superar 255 caracteres.',
  messageShort: 'Escribe un mensaje de al menos 15 caracteres.',
  messageLong: 'El mensaje no debe superar 3000 caracteres.',
  serverEmail:
    'Revisa el correo: debe ser válido y tener un dominio que acepte correo.',
  serverName:
    'Revisa el nombre: es obligatorio y debe tener hasta 100 caracteres.',
  serverSubject: 'Revisa el asunto: debe tener hasta 255 caracteres.',
  serverMessage: 'Revisa el mensaje: debe tener entre 15 y 3000 caracteres.',
  footer: 'Ingeniería de producto. Con criterio.',
  backToTop: 'Volver arriba',
}

export type Copy = { [Key in keyof typeof es]: string }

const en: Copy = {
  skip: 'Skip to content',
  navLabel: 'Main navigation',
  language: 'Change language',
  cases: 'Architecture',
  philosophy: 'Philosophy',
  leadership: 'Leadership',
  career: 'Experience',
  contact: 'Let’s talk',
  loading: 'Loading portfolio…',
  updating: 'Updating language…',
  retry: 'Try again',
  loadError: 'I couldn’t load the portfolio. Please try again.',
  timeout: 'The connection is taking longer than expected. Please try again.',
  heroFirst: 'Architecture with purpose.',
  heroSecond: 'Code with intention.',
  heroFallback:
    'Product engineering, architecture decisions and technical leadership with direct involvement in the code.',
  explore: 'Explore decisions',
  startConversation: 'Start a conversation',
  terminalLabel: 'A way of thinking about systems',
  terminalTitle: 'engineering.md',
  terminalProblem: 'Understand the problem',
  terminalDecide: 'Make the trade-offs explicit',
  terminalBuild: 'Build, measure, improve',
  terminalPrinciple: 'Clarity scales, too.',
  metricsLabel: 'Results from a production case',
  p99: 'P99 latency',
  peak: 'Events per second',
  before: 'before',
  after: 'after',
  metricsNote: 'AdTech case · production metrics',
  skillsEyebrow: '04 / tools',
  skillsTitle: 'The stack follows the problem.',
  skillsDescription:
    'Technology chosen with context. Systems that can be operated and maintained.',
  casesEyebrow: '02 / production decisions',
  casesTitle: 'Decisions, not recipes.',
  casesDescription:
    'The context, the solution and the cost of choosing it. How I approach architecture.',
  context: 'Context',
  problem: 'The problem',
  solution: 'The decision',
  tradeoffs: 'The trade-offs',
  impact: 'Impact',
  technicalDetails: 'Explore the technical reasoning',
  metricBefore: 'P99 before',
  metricAfter: 'P99 after',
  metricPeak: 'Peak events',
  philosophyEyebrow: '01 / approach',
  philosophyTitle: 'Fewer assumptions. More evidence.',
  philosophyDescription:
    'Principles that carry through to code, incidents and every product decision.',
  leadershipEyebrow: '03 / technical leadership',
  leadershipTitle: 'The team is architecture, too.',
  leadershipDescription:
    'Create the context for other people to make better decisions.',
  careerEyebrow: '05 / experience',
  careerTitle: 'Close to the code. Responsible for the direction.',
  contactEyebrow: '06 / conversation',
  contactTitle: 'What problem are we solving?',
  contactDescription:
    'Tell me about the context, the friction and what needs to change. Let’s start by understanding it.',
  contactNote: 'Your message is used only to respond to this conversation.',
  name: 'Name',
  email: 'Email address',
  subject: 'Subject',
  message: 'Message',
  optional: 'optional',
  namePlaceholder: 'Your name',
  emailPlaceholder: 'you@company.com',
  subjectPlaceholder: 'What are you working on?',
  messagePlaceholder:
    'The context, the challenge and what you’d like to achieve…',
  messageHint: 'Between 15 and 3000 characters.',
  send: 'Send message',
  sending: 'Sending…',
  received: 'Request received. Thanks for sharing the context.',
  contactError:
    'I couldn’t send the message. Check your connection and try again.',
  contactTimeout:
    'I couldn’t confirm receipt. Wait before sending again to avoid duplicates.',
  invalidContact: 'Review the highlighted fields before sending.',
  rateLimit:
    'You’ve sent several requests. Wait {minutes} min before trying again.',
  nameRequired: 'Enter your name.',
  nameLong: 'Your name must not exceed 100 characters.',
  emailInvalid: 'Enter a valid email address, up to 255 characters.',
  subjectLong: 'The subject must not exceed 255 characters.',
  messageShort: 'Write a message of at least 15 characters.',
  messageLong: 'The message must not exceed 3000 characters.',
  serverEmail:
    'Check your email: it must be valid and use a domain that accepts email.',
  serverName:
    'Check your name: it is required and must have at most 100 characters.',
  serverSubject: 'Check the subject: it must have at most 255 characters.',
  serverMessage:
    'Check your message: it must have between 15 and 3000 characters.',
  footer: 'Product engineering. With purpose.',
  backToTop: 'Back to top',
}

export function getCopy(language: Language): Copy {
  return language === 'en' ? en : es
}
